# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-03-20 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='ipaddress',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
