# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-03-21 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_data_ipaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='iplist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('idate', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
