# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-03-21 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0003_iplist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iplist',
            name='count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
